export const products = [
    {
        id: 1,
        imgs: ["/bej1.jpg", "/bej2.jpg", "/bej3.jpg", "/bej4.jpg"],
        title: 'Product 1',
        color: 'black',
        category: 'Activewear',
        subcategory: 'Leggings & Yoga Pants',
        size: 'S',
        quantity: 10,
        bestSellerStatus: 'Best Seller',
        newArrival: 'Y',  //'Y' and 'N'
        currency: '$',
        price: 50,
        promo: 'Y',
        promoPrice: 45,
        availability: 'Available', // Available and Out of Stock
    },
    {
        id: 2,
        imgs: ["/purple1.jpg", "/purple2.jpg", "/purple3.jpg", "/purple4.jpg"],
        title: 'Product 2',
        color: 'cream',
        category: 'Activewear',
        subcategory: 'Matching Sets',
        size: 'M',
        quantity: 10,
        bestSellerStatus: 'Best Seller',
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'Y',
        promoPrice: 45,
        availability: 'Available',
    },
    {
        id: 3,
        imgs: ["/corset.jpg"],
        title: 'Product 3',
        color: 'orange',
        category: 'Accessories',
        subcategory: 'Corsets',
        size: null,
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Out of Stock',
    },
    {
        id: 4,
        imgs: ["/swim1.jpg", "/swim2.jpg", "/swim3.jpg", "/swim4.jpg"],
        title: 'Product 4',
        color: 'cream',
        category: 'Swimwear',
        subcategory: 'Swimwear',
        size: 'S',
        quantity: 10,
        bestSellerStatus: 'Best Seller',
        newArrival: 'Y',
        currency: '$',
        price: 50,
        promo: 'Y',
        promoPrice: 45,
        availability: 'Available',
    },
    {
        id: 5,
        imgs: ["/sb1.jpg", "/sb2.jpg", "/sb3.jpg", "/sb4.jpg"],
        title: 'Product 5',
        color: 'purple',
        category: 'Accessories',
        subcategory: 'Sport Bags',
        size: null,
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'out of stock'
    },
    {
        id: 6,
        imgs: ["/purple1.jpg", "/purple2.jpg", "/purple3.jpg", "/purple4.jpg"],
        title: 'Product 6',
        color: 'blue',
        category: 'Activewear',
        subcategory: 'Long-sleeve workout tops',
        size: 'L',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },
    {
        id: 7,
        imgs: ["/black2.jpg", "/black3.jpg", "/black2.jpg", "/black3.jpg"],
        title: 'Product 7',
        color: 'white',
        category: 'Activewear',
        subcategory: 'Leggings & Yoga Pants',
        size: 'S',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },
    {
        id: 8,
        imgs: ["/bej1.jpg", "/bej2.jpg", "/bej3.jpg", "/bej4.jpg"],
        title: 'Product 8',
        color: 'purple',
        category: 'Activewear',
        subcategory: 'Tennis Shorts',
        size: 'M',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },
    {
        id: 9,
        imgs: ["/purple1.jpg", "/purple2.jpg", "/purple3.jpg", "/purple4.jpg"],
        title: 'Product 9',
        color: 'grey',
        category: 'Activewear',
        subcategory: 'Shorts',
        size: 'S',
        quantity: 10,
        bestSellerStatus: 'Best Seller',
        newArrival: 'Y',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },
    {
        id: 10,
        imgs: ["/swim1.jpg", "/swim2.jpg", "/swim3.jpg", "/swim4.jpg"],
        title: 'Product 10',
        color: 'pink',
        category: 'Activewear',
        subcategory: 'T-shirts',
        size: 'L',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Out of Stock',
    },
    {
        id: 11,
        imgs: ["/purple1.jpg", "/purple2.jpg", "/purple3.jpg", "/purple4.jpg"],
        title: 'Product 11',
        color: 'indigo',
        category: 'Activewear',
        subcategory: 'Leggings & Yoga Pants',
        size: 'M',
        quantity: 10,
        bestSellerStatus: 'Best Seller',
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },
    {
        id: 12,
        imgs: ["/wh1.jpg", "/wh2.jpg", "/wh3.jpg"],
        title: 'Product 12',
        color: 'yellow',
        category: 'Activewear',
        subcategory: 'Leggings & Yoga Pants',
        size: 'M',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Out of Stock',
    },
    {
        id: 13,
        imgs: ["/purple1.jpg", "/purple2.jpg", "/purple3.jpg", "/purple4.jpg"],
        title: 'Product 13',
        color: 'green',
        category: 'Activewear',
        subcategory: 'Sport Bras',
        size: 'S',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'Y',
        promoPrice: 45,
        availability: 'Available',
    },
    {
        id: 14,
        imgs: ["/bej1.jpg", "/bej2.jpg", "/bej3.jpg", "bej4.jpg"],
        title: 'Product 14',
        color: 'blue',
        category: 'Activewear',
        subcategory: 'Matching Sets',
        size: 'S',
        quantity: 10,
        bestSellerStatus: 'Best Seller',
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'Y',
        promoPrice: 45,
        availability: 'Available',
    },
    {
        id: 15,
        imgs: ["/black3.jpg", "/black2.jpg","/black3.jpg","/black2.jpg"],
        title: 'Product 15',
        color: 'pink',
        category: 'Activewear',
        subcategory: 'Long-sleeve workout tops',
        size: 'M',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'Y',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },
    {
        id: 16,
        imgs: ["/corset.jpg"],
        title: 'Product 16',
        color: 'orange',
        category: 'Accessories',
        subcategory: 'Corsets',
        size: 'S',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'Y',
        promoPrice: 45,
        availability: 'Out of Stock',
    },
    {
        id: 17,
        imgs: ["/swim1.jpg", "/swim2.jpg", "/swim3.jpg", "/swim4.jpg"],
        title: 'Product 17',
        color: 'cream',
        category: 'Swimwear',
        subcategory: 'Swimwear',
        size: 'S',
        quantity: 10,
        bestSellerStatus: 'Best Seller',
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },
    {
        id: 18,
        imgs: ["/sb1.jpg", "/sb2.jpg", "/sb3.jpg", "/sb4.jpg"],
        title: 'Product 18',
        color: 'black',
        category: 'Accessories',
        subcategory: 'Sport Bags',
        size: null,
        quantity: 10,
        bestSellerStatus: 'Best Seller',
        newArrival: 'Y',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },

    {
        id: 19,
        imgs: ["/purple1.jpg", "/purple2.jpg", "/purple3.jpg", "/purple4.jpg"],
        title: 'Product 19',
        color: 'purple',
        category: 'Activewear',
        subcategory: 'Tennis Shorts',
        size: 'M',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Out of Stock',
    },
    {
        id: 20,
        imgs: ["/corset.jpg"],
        title: 'Product 20',
        color: 'orange',
        category: 'Accessories',
        subcategory: 'Corsets',
        size: 'M',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'Y',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Out of Stock',
    },
    {
        id: 21,
        imgs: ["/bej1.jpg", "/bej2.jpg", "/bej3.jpg", "bej4.jpg"],
        title: 'Product 21',
        color: 'grey',
        category: 'Activewear',
        subcategory: 'T-shirts',
        size: 'M',
        quantity: 10,
        bestSellerStatus: 'Best Seller',
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },
    {
        id: 22,
        imgs: ["/rb.jpg"],
        title: 'Product 22',
        color: 'blue',
        category: 'Accessories',
        subcategory: 'Resistance Bands',
        size: null,
        quantity: 10,
        bestSellerStatus: 'Best Seller',
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null, availability: 'Available',
    },
    {
        id: 23,
        imgs: ["/corset.jpg"],
        title: 'Product 23',
        color: 'green',
        category: 'Activewear',
        subcategory: 'Sport Bras',
        size: 'M',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Out of Stock',
    },
    {
        id: 24,
        imgs: ["/purple1.jpg", "/purple2.jpg", "/purple3.jpg", "/purple4.jpg"],
        title: 'Product 24',
        color: 'indigo',
        category: 'Activewear',
        subcategory: 'Tennis Shorts',
        size: 'S',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },
    {
        id: 25,
        title: 'Product 25',
        imgs: ["/rb.jpg"],
        color: 'orange',
        category: 'Accessories',
        subcategory: 'Resistance Bands',
        size: null,
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },
    {
        id: 26,
        imgs: ["/sb1.jpg", "/sb2.jpg", "/sb3.jpg", "/sb4.jpg"],
        title: 'Product 26',
        color: 'cream',
        category: 'Accessories',
        subcategory: 'Sport Bags',
        size: null,
        quantity: 10,
        bestSellerStatus: 'Best Seller',
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Out of Stock',
    },
    {
        id: 27,
        imgs: ["/bej1.jpg", "/bej2.jpg", "/bej3.jpg", "bej4.jpg"],
        title: 'Product 27',
        color: 'pink',
        category: 'Activewear',
        subcategory: 'Tennis Shorts',
        size: 'S',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },
    {
        id: 28,
        imgs: ["/purple1.jpg", "/purple2.jpg", "/purple3.jpg", "/purple4.jpg"],
        title: 'Product 28',
        color: 'black',
        category: 'Activewear',
        subcategory: 'Long-sleeve workout tops',
        size: 'M',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },
    {
        id: 29,
        imgs: ["/black2.jpg", "/black3.jpg", "/black2.jpg", "/black3.jpg"],
        title: 'Product 29',
        color: 'purple',
        category: 'Activewear',
        subcategory: 'Leggings & Yoga Pants',
        size: 'S',
        quantity: 10,
        bestSellerStatus: 'Best Seller',
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null, availability: 'Available',
    },
    {
        id: 30,
        imgs: ["/purple1.jpg", "/purple2.jpg", "/purple3.jpg", "/purple4.jpg"],
        title: 'Product 30',
        color: 'orange',
        category: 'Activewear',
        subcategory: 'Sport Bras',
        size: 'M',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },
    {
        id: 31,
        imgs: ["/corset.jpg"],
        title: 'Product 31',
        color: 'orange',
        category: 'Accessories',
        subcategory: 'Corsets',
        size: 'S',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Out of Stock',
    },
    {
        id: 32,
        imgs: ["/purple1.jpg", "/purple2.jpg", "/purple3.jpg", "/purple4.jpg"],
        title: 'Product 32',
        color: 'white',
        category: 'Activewear',
        subcategory: 'Tops & Sport Bras',
        size: 'M',
        quantity: 10,
        bestSellerStatus: 'Best Seller',
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Out of Stock',
    },
    {
        id: 33,
        imgs: ["/bej1.jpg", "/bej2.jpg", "/bej3.jpg", "bej4.jpg"],
        title: 'Product 33',
        color: 'yellow',
        category: 'Activewear',
        subcategory: 'Matching Sets',
        size: 'S',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null, availability: 'Available',
    },
    {
        id: 34,
        imgs: ["/purple1.jpg", "/purple2.jpg", "/purple3.jpg", "/purple4.jpg"],
        title: 'Product 34',
        color: 'mint',
        category: 'Activewear',
        subcategory: 'Leggings & Yoga Pants',
        size: 'S',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Out of Stock',
    },
    {
        id: 35,
        imgs: ["/purple1.jpg", "/purple2.jpg", "/purple3.jpg", "/purple4.jpg"],
        title: 'Product 35',
        color: 'black',
        category: 'Activewear',
        subcategory: 'Sport Bras',
        size: 'S',
        quantity: 10,
        bestSellerStatus: 'Best Seller',
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },
    {
        id: 36,
        imgs: ["/sb1.jpg", "/sb2.jpg", "/sb3.jpg", "/sb4.jpg"],
        title: 'Product 36',
        color: 'purple',
        category: 'Accessories',
        subcategory: 'Sport Bags',
        size: null,
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },
    {
        id: 37,
        imgs: ["/corset.jpg"],
        title: 'Product 37',
        color: 'pink',
        category: 'Activewear',
        subcategory: 'Tennis Shorts',
        size: 'S',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },
    {
        id: 38,
        imgs: ["/purple1.jpg", "/purple2.jpg", "/purple3.jpg", "/purple4.jpg"],
        title: 'Product 38',
        color: 'blue',
        category: 'Activewear',
        subcategory: 'Long-sleeve workout tops',
        size: 'S',
        quantity: 10,
        bestSellerStatus: 'Best Seller',
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Out of Stock',
    },
    {
        id: 39,
        imgs: ["/purple1.jpg", "/purple2.jpg", "/purple3.jpg", "/purple4.jpg"],
        title: 'Product 39',
        color: 'orange',
        category: 'Activewear',
        subcategory: 'Leggings & Yoga Pants',
        size: 'S',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },
    {
        id: 40,
        imgs: ["/bej1.jpg", "/bej2.jpg", "/bej3.jpg", "bej4.jpg"],
        title: 'Product 40',
        color: 'green',
        category: 'Activewear',
        subcategory: 'Sport Bras',
        size: 'S',
        quantity: 10,
        bestSellerStatus: 'Best Seller',
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },
    {
        id: 41,
        imgs: ["/swim1.jpg", "/swim2.jpg", "/swim3.jpg", "/swim4.jpg"],
        title: 'Product 41',
        color: 'indigo',
        category: 'Swimwear',
        subcategory: 'Swimwear',
        size: 'M',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },
    {
        id: 42,
        imgs: ["/purple1.jpg", "/purple2.jpg", "/purple3.jpg", "/purple4.jpg"],
        title: 'Product 42',
        color: 'yellow',
        category: 'Activewear',
        subcategory: 'Matching Sets',
        size: 'S',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Out of Stock',
    },
    {
        id: 43,
        imgs: ["/bej1.jpg", "/bej2.jpg", "/bej3.jpg", "bej4.jpg"],
        title: 'Product 43',
        color: 'grey',
        category: 'Activewear',
        subcategory: 'Tennis Shorts',
        size: 'L',
        quantity: 10,
        bestSellerStatus: 'Best Seller',
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },
    {
        id: 44,
        imgs: ["/purple1.jpg", "/purple2.jpg", "/purple3.jpg", "/purple4.jpg"],
        title: 'Product 44',
        color: 'mint',
        category: 'Activewear',
        subcategory: 'Tops & Sport Bras',
        size: 'S',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },
    {
        id: 45,
        imgs: ["/sb1.jpg", "/sb2.jpg", "/sb3.jpg", "/sb4.jpg"],
        title: 'Product 45',
        color: 'white',
        category: 'Accessories',
        subcategory: 'Sport Bags',
        size: null,
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },
    {
        id: 46,
        imgs: ["/bej1.jpg", "/bej2.jpg", "/bej3.jpg", "bej4.jpg"],
        title: 'Product 46',
        color: 'pink',
        category: 'Activewear',
        subcategory: 'Long-sleeve workout tops',
        size: 'S',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },
    {
        id: 47,
        imgs: ["/corset.jpg"],
        title: 'Product 47',
        color: 'orange',
        category: 'Accessories',
        subcategory: 'Corsets',
        size: 'S',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Out of Stock',
    },
    {
        id: 48,
        imgs: ["/purple1.jpg", "/purple2.jpg", "/purple3.jpg", "/purple4.jpg"],
        title: 'Product 48',
        color: 'cream',
        category: 'Activewear',
        subcategory: 'Tops & Sport Bras',
        size: 'S',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Out of Stock',
    },
    {
        id: 49,
        imgs: ["/swim1.jpg", "/swim2.jpg", "/swim3.jpg", "/swim4.jpg"],
        title: 'Product 49',
        color: 'green',
        category: 'Swimwear',
        subcategory: 'Swimwear',
        size: 'M',
        quantity: 10,
        bestSellerStatus: 'Best Seller',
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },
    {
        id: 50,
        imgs: ["/sb1.jpg", "/sb2.jpg", "/sb3.jpg", "/sb4.jpg"],
        title: 'Product 50',
        color: 'grey',
        category: 'Accessories',
        subcategory: 'Sport Bag',
        size: null,
        quantity: 10,
        bestSellerStatus: 'Best Seller',
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },
];

export const getProducts = () => {
    return products;
}

//cream structura generala pentru a adauga aici produse noi
export const getProductById = (id) => {
    const foundItem = products.find(product => product.id === id);
    const defaultItem = {
        id: null,
        imgs: ["/purple1.jpg", "/purple2.jpg", "/purple3.jpg", "/purple4.jpg"],
        img2: '',
        img3: '',
        title: '',
        color: '',
        category: 'Activewear',
        subcategory: '',
        size: '',

        quantity: 10, bestSellerStatus: '',
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: '',
    };
    return foundItem ? foundItem : defaultItem;
};

//cream o functie care va adauga produse in lista initiala, dar va si modifica produsul existent daca este cazul. Acum trebuie sa verificam daca produsul are id, atunci trebuie sa il gasim si sa rescriem proprietatile lui cu ceea ce primim aici, ceea ce insemana ca el a fost modificat, iar daca id este null, atunci trebuie sa setam un nou atribut id si sa il adaugam in lista
export const saveProduct = (product) => {
    if (!product.id) {//daca nu avem asa produs
        product.id = products.length + 1;
        products.push(product);
    } else {
        const productIndex = products.findIndex(item => item.id === product.id);

        products[productIndex] = product;
    }
};

//aceatsa functie va gasi indexul produsului si il va sterge prin splice -anume item de pe acel index
export const deleteProduct = (id) => {
    const foundIndex = products.findIndex(product => product.id === id);

    if (foundIndex > -1) {
        products.splice(foundIndex, 1);
    }
};