export const products = [
    {
        id: 1,
        imgs: ["/bej1.jpg", "/bej2.jpg", "/bej3.jpg", "/bej4.jpg"],
        title: 'Product 1',
        titleCode: 'product_1',
        color: 'black',
        category: 'Activewear',
        subcategory: 'Leggings & Yoga Pants',
        subcategoryCode: 'leggings_and_yoga_pants',
        size: 'S',
        quantity: 10,
        bestSellerStatus: 'Best Seller',
        newArrival: 'Y',  //'Y' and 'N'
        currency: '$',
        price: 100,
        promo: 'Y',
        promoPrice: 45,
        availability: 'Available', // Available and Out of Stock
    },
    {
        id: 2,
        imgs: ["/purple1.jpg", "/purple2.jpg", "/purple3.jpg", "/purple4.jpg"],
        title: 'Product 2',
        titleCode: 'product_2',
        color: 'cream',
        category: 'Activewear',
        subcategory: 'Matching Sets',
        subcategoryCode: 'matching_sets',
        size: 'M',
        quantity: 10,
        bestSellerStatus: 'Best Seller',
        newArrival: 'N',
        currency: '$',
        price: 90,
        promo: 'Y',
        promoPrice: 45,
        availability: 'Available',
    },
    {
        id: 3,
        imgs: ["/corset.jpg"],
        title: 'Product 3',
        titleCode: 'product_3',
        color: 'orange',
        category: 'Accessories',
        subcategory: 'Corsets',
        subcategoryCode: 'corsets',
        size: null,
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 200,
        promo: 'N',
        promoPrice: null,
        availability: 'Out of Stock',
    },
    {
        id: 4,
        imgs: ["/swim1.jpg", "/swim2.jpg", "/swim3.jpg", "/swim4.jpg"],
        title: 'Product 4',
        titleCode: 'product_4',
        color: 'cream',
        category: 'Swimwear',
        subcategory: 'Swimwear',
        subcategoryCode: 'swimwear',
        size: 'S',
        quantity: 10,
        bestSellerStatus: 'Best Seller',
        newArrival: 'Y',
        currency: '$',
        price: 70,
        promo: 'Y',
        promoPrice: 45,
        availability: 'Available',
    },
    {
        id: 5,
        imgs: ["/sb1.jpg", "/sb2.jpg", "/sb3.jpg", "/sb4.jpg"],
        title: 'Product 5',
        titleCode: 'product_5',
        color: 'purple',
        category: 'Accessories',
        subcategory: 'Sport Bags',
        subcategoryCode: 'sport_bags',
        size: null,
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 80,
        promo: 'N',
        promoPrice: null,
        availability: 'out of stock'
    },
    {
        id: 6,
        imgs: ["/purple1.jpg", "/purple2.jpg", "/purple3.jpg", "/purple4.jpg"],
        title: 'Product 6',
        titleCode: 'product_6',
        color: 'blue',
        category: 'Activewear',
        subcategory: 'Long-sleeve workout tops',
        subcategoryCode: 'long-sleeve_workout_tops',
        size: 'L',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 70,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },
    {
        id: 7,
        imgs: ["/black2.jpg", "/black3.jpg", "/black2.jpg", "/black3.jpg"],
        title: 'Product 7',
        titleCode: 'product_7',
        color: 'white',
        category: 'Activewear',
        subcategory: 'Leggings & Yoga Pants',
        subcategoryCode: 'leggings_and_yoga_pants',
        size: 'S',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 90,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },
    {
        id: 8,
        imgs: ["/bej1.jpg", "/bej2.jpg", "/bej3.jpg", "/bej4.jpg"],
        title: 'Product 8',
        titleCode: 'product_8',
        color: 'purple',
        category: 'Activewear',
        subcategory: 'Tennis Shorts',
        subcategoryCode: 'tennis_shorts',
        size: 'M',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },
    {
        id: 9,
        imgs: ["/purple1.jpg", "/purple2.jpg", "/purple3.jpg", "/purple4.jpg"],
        title: 'Product 9',
        titleCode: 'product_9',
        color: 'grey',
        category: 'Activewear',
        subcategory: 'Tennis Shorts',
        subcategoryCode: 'tennis_shorts',
        size: 'S',
        quantity: 10,
        bestSellerStatus: 'Best Seller',
        newArrival: 'Y',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },
    {
        id: 10,
        imgs: ["/swim1.jpg", "/swim2.jpg", "/swim3.jpg", "/swim4.jpg"],
        title: 'Product 10',
        titleCode: 'product_10',
        color: 'pink',
        category: 'Activewear',
        subcategory: 'T-shirts',
        subcategoryCode: 'T-shirts',
        size: 'L',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 60,
        promo: 'N',
        promoPrice: null,
        availability: 'Out of Stock',
    },
    {
        id: 11,
        imgs: ["/purple1.jpg", "/purple2.jpg", "/purple3.jpg", "/purple4.jpg"],
        title: 'Product 11',
        titleCode: 'product_11',
        color: 'indigo',
        category: 'Activewear',
        subcategory: 'Leggings & Yoga Pants',
        subcategoryCode: 'leggings_and_yoga_pants',
        size: 'M',
        quantity: 10,
        bestSellerStatus: 'Best Seller',
        newArrival: 'N',
        currency: '$',
        price: 80,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },
    {
        id: 12,
        imgs: ["/wh1.jpg", "/wh2.jpg", "/wh3.jpg"],
        title: 'Product 12',
        titleCode: 'product_12',
        color: 'yellow',
        category: 'Activewear',
        subcategory: 'Leggings & Yoga Pants',
        subcategoryCode: 'leggings_and_yoga_pants',
        size: 'M',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 75,
        promo: 'N',
        promoPrice: null,
        availability: 'Out of Stock',
    },
    {
        id: 13,
        imgs: ["/purple1.jpg", "/purple2.jpg", "/purple3.jpg", "/purple4.jpg"],
        title: 'Product 13',
        titleCode: 'product_13',
        color: 'green',
        category: 'Activewear',
        subcategory: 'Sport Bras',
        subcategoryCode: 'sport_bras',
        size: 'S',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 30,
        promo: 'Y',
        promoPrice: 45,
        availability: 'Available',
    },
    {
        id: 14,
        imgs: ["/bej1.jpg", "/bej2.jpg", "/bej3.jpg", "bej4.jpg"],
        title: 'Product 14',
        titleCode: 'product_14',
        color: 'blue',
        category: 'Activewear',
        subcategory: 'Matching Sets',
        subcategoryCode: 'matching_sets',
        size: 'S',
        quantity: 10,
        bestSellerStatus: 'Best Seller',
        newArrival: 'N',
        currency: '$',
        price: 200,
        promo: 'Y',
        promoPrice: 45,
        availability: 'Available',
    },
    {
        id: 15,
        imgs: ["/black3.jpg", "/black2.jpg", "/black3.jpg", "/black2.jpg"],
        title: 'Product 15',
        titleCode: 'product_15',
        color: 'pink',
        category: 'Activewear',
        subcategory: 'Long-sleeve workout tops',
        subcategoryCode: 'long-sleeve_workout_tops',
        size: 'M',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'Y',
        currency: '$',
        price: 90,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },
    {
        id: 16,
        imgs: ["/corset.jpg"],
        title: 'Product 16',
        titleCode: 'product_16',
        color: 'orange',
        category: 'Accessories',
        subcategory: 'Corsets',
        subcategoryCode: 'corsets',
        size: 'S',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 60,
        promo: 'Y',
        promoPrice: 45,
        availability: 'Out of Stock',
    },
    {
        id: 17,
        imgs: ["/swim1.jpg", "/swim2.jpg", "/swim3.jpg", "/swim4.jpg"],
        title: 'Product 17',
        titleCode: 'product_17',
        color: 'cream',
        category: 'Swimwear',
        subcategory: 'Swimwear',
        subcategoryCode: 'swimwear',
        size: 'S',
        quantity: 10,
        bestSellerStatus: 'Best Seller',
        newArrival: 'N',
        currency: '$',
        price: 120,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },
    {
        id: 18,
        imgs: ["/sb1.jpg", "/sb2.jpg", "/sb3.jpg", "/sb4.jpg"],
        title: 'Product 18',
        titleCode: 'product_18',
        color: 'black',
        category: 'Accessories',
        subcategory: 'Sport Bags',
        subcategoryCode: 'sport_bags',
        size: null,
        quantity: 10,
        bestSellerStatus: 'Best Seller',
        newArrival: 'Y',
        currency: '$',
        price: 80,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },

    {
        id: 19,
        imgs: ["/purple1.jpg", "/purple2.jpg", "/purple3.jpg", "/purple4.jpg"],
        title: 'Product 19',
        titleCode: 'product_19',
        color: 'purple',
        category: 'Activewear',
        subcategory: 'Tennis Shorts',
        subcategoryCode: 'tennis_shorts',
        size: 'M',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Out of Stock',
    },
    {
        id: 20,
        imgs: ["/corset.jpg"],
        title: 'Product 20',
        titleCode: 'product_20',
        color: 'orange',
        category: 'Accessories',
        subcategory: 'Corsets',
        subcategoryCode: 'corsets',
        size: 'M',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'Y',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Out of Stock',
    },
    {
        id: 21,
        imgs: ["/bej1.jpg", "/bej2.jpg", "/bej3.jpg", "bej4.jpg"],
        title: 'Product 21',
        titleCode: 'product_21',
        color: 'grey',
        category: 'Activewear',
        subcategory: 'T-shirts',
        subcategoryCode: 'T-shirts',
        size: 'M',
        quantity: 10,
        bestSellerStatus: 'Best Seller',
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },
    {
        id: 22,
        imgs: ["/rb.jpg"],
        title: 'Product 22',
        titleCode: 'product_22',
        color: 'blue',
        category: 'Accessories',
        subcategory: 'Resistance Bands',
        subcategoryCode: 'resistance_bands',
        size: null,
        quantity: 10,
        bestSellerStatus: 'Best Seller',
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null, availability: 'Available',
    },
    {
        id: 23,
        imgs: ["/corset.jpg"],
        title: 'Product 23',
        titleCode: 'product_23',
        color: 'green',
        category: 'Activewear',
        subcategory: 'Sport Bras',
        subcategoryCode: 'sport_bras',
        size: 'M',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Out of Stock',
    },
    {
        id: 24,
        imgs: ["/purple1.jpg", "/purple2.jpg", "/purple3.jpg", "/purple4.jpg"],
        title: 'Product 24',
        titleCode: 'product_24',
        color: 'indigo',
        category: 'Activewear',
        subcategory: 'Tennis Shorts',
        subcategoryCode: 'tennis_shorts',
        size: 'S',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },
    {
        id: 25,
        title: 'Product 25',
        imgs: ["/rb.jpg"],
        titleCode: 'product_25',
        color: 'orange',
        category: 'Accessories',
        subcategory: 'Resistance Bands',
        subcategoryCode: 'resistance_bands',
        size: null,
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },
    {
        id: 26,
        imgs: ["/sb1.jpg", "/sb2.jpg", "/sb3.jpg", "/sb4.jpg"],
        title: 'Product 26',
        titleCode: 'product_26',
        color: 'cream',
        category: 'Accessories',
        subcategory: 'Sport Bags',
        subcategoryCode: 'sport_bags',
        size: null,
        quantity: 10,
        bestSellerStatus: 'Best Seller',
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Out of Stock',
    },
    {
        id: 27,
        imgs: ["/bej1.jpg", "/bej2.jpg", "/bej3.jpg", "bej4.jpg"],
        title: 'Product 27',
        titleCode: 'product_27',
        color: 'pink',
        category: 'Activewear',
        subcategory: 'Tennis Shorts',
        subcategoryCode: 'tennis_shorts',
        size: 'S',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },
    {
        id: 28,
        imgs: ["/purple1.jpg", "/purple2.jpg", "/purple3.jpg", "/purple4.jpg"],
        title: 'Product 28',
        titleCode: 'product_28',
        color: 'black',
        category: 'Activewear',
        subcategory: 'Long-sleeve workout tops',
        subcategoryCode: 'long-sleeve_workout_tops',
        size: 'M',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },
    {
        id: 29,
        imgs: ["/black2.jpg", "/black3.jpg", "/black2.jpg", "/black3.jpg"],
        title: 'Product 29',
        titleCode: 'product_29',
        color: 'purple',
        category: 'Activewear',
        subcategory: 'Leggings & Yoga Pants',
        subcategoryCode: 'leggings_and_yoga_pants',
        size: 'S',
        quantity: 10,
        bestSellerStatus: 'Best Seller',
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null, 
        availability: 'Available',
    },
    {
        id: 30,
        imgs: ["/purple1.jpg", "/purple2.jpg", "/purple3.jpg", "/purple4.jpg"],
        title: 'Product 30',
        titleCode: 'product_30',
        color: 'orange',
        category: 'Activewear',
        subcategory: 'Sport Bras',
        subcategoryCode: 'sport_bras',
        size: 'M',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },
    {
        id: 31,
        imgs: ["/corset.jpg"],
        title: 'Product 31',
        titleCode: 'product_31',
        color: 'orange',
        category: 'Accessories',
        subcategory: 'Corsets',
        subcategoryCode: 'corsets',
        size: 'S',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Out of Stock',
    },
    {
        id: 32,
        imgs: ["/purple1.jpg", "/purple2.jpg", "/purple3.jpg", "/purple4.jpg"],
        title: 'Product 32',
        titleCode: 'product_32',
        color: 'white',
        category: 'Activewear',
        subcategory: 'Tops & Sport Bras',
        subcategoryCode: 'tops_and_sport_bras',
        size: 'M',
        quantity: 10,
        bestSellerStatus: 'Best Seller',
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Out of Stock',
    },
    {
        id: 33,
        imgs: ["/bej1.jpg", "/bej2.jpg", "/bej3.jpg", "bej4.jpg"],
        title: 'Product 33',
        titleCode: 'product_33',
        color: 'yellow',
        category: 'Activewear',
        subcategory: 'Matching Sets',
        subcategoryCode: 'matching_sets',
        size: 'S',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null, availability: 'Available',
    },
    {
        id: 34,
        imgs: ["/purple1.jpg", "/purple2.jpg", "/purple3.jpg", "/purple4.jpg"],
        title: 'Product 34',
        titleCode: 'product_34',
        color: 'mint',
        category: 'Activewear',
        subcategory: 'Leggings & Yoga Pants',
        subcategoryCode: 'leggings_and_yoga_pants',
        size: 'S',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Out of Stock',
    },
    {
        id: 35,
        imgs: ["/purple1.jpg", "/purple2.jpg", "/purple3.jpg", "/purple4.jpg"],
        title: 'Product 35',
        titleCode: 'product_35',
        color: 'black',
        category: 'Activewear',
        subcategory: 'Sport Bras',
        subcategoryCode: 'sport_bras',
        size: 'S',
        quantity: 10,
        bestSellerStatus: 'Best Seller',
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },
    {
        id: 36,
        imgs: ["/sb1.jpg", "/sb2.jpg", "/sb3.jpg", "/sb4.jpg"],
        title: 'Product 36',
        titleCode: 'product_36',
        color: 'purple',
        category: 'Accessories',
        subcategory: 'Sport Bags',
        subcategoryCode: 'sport_bags',
        size: null,
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },
    {
        id: 37,
        imgs: ["/corset.jpg"],
        title: 'Product 37',
        titleCode: 'product_37',
        color: 'pink',
        category: 'Activewear',
        subcategory: 'Tennis Shorts',
        subcategoryCode: 'tennis_shorts',
        size: 'S',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },
    {
        id: 38,
        imgs: ["/purple1.jpg", "/purple2.jpg", "/purple3.jpg", "/purple4.jpg"],
        title: 'Product 38',
        titleCode: 'product_38',
        color: 'blue',
        category: 'Activewear',
        subcategory: 'Long-sleeve workout tops',
        subcategoryCode: 'long-sleeve_workout_tops',
        size: 'S',
        quantity: 10,
        bestSellerStatus: 'Best Seller',
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Out of Stock',
    },
    {
        id: 39,
        imgs: ["/purple1.jpg", "/purple2.jpg", "/purple3.jpg", "/purple4.jpg"],
        title: 'Product 39',
        titleCode: 'product_39',
        color: 'orange',
        category: 'Activewear',
        subcategory: 'Leggings & Yoga Pants',
        subcategoryCode: 'leggings_and_yoga_pants',
        size: 'S',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },
    {
        id: 40,
        imgs: ["/bej1.jpg", "/bej2.jpg", "/bej3.jpg", "bej4.jpg"],
        title: 'Product 40',
        titleCode: 'product_40',
        color: 'green',
        category: 'Activewear',
        subcategory: 'Sport Bras',
        subcategoryCode: 'sport_bras',
        size: 'S',
        quantity: 10,
        bestSellerStatus: 'Best Seller',
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },
    {
        id: 41,
        imgs: ["/swim1.jpg", "/swim2.jpg", "/swim3.jpg", "/swim4.jpg"],
        title: 'Product 41',
        titleCode: 'product_41',
        color: 'indigo',
        category: 'Swimwear',
        subcategory: 'Swimwear',
        subcategoryCode: 'swimwear',
        size: 'M',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },
    {
        id: 42,
        imgs: ["/purple1.jpg", "/purple2.jpg", "/purple3.jpg", "/purple4.jpg"],
        title: 'Product 42',
        titleCode: 'product_42',
        color: 'yellow',
        category: 'Activewear',
        subcategory: 'Matching Sets',
        subcategoryCode: 'matching_sets',
        size: 'S',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Out of Stock',
    },
    {
        id: 43,
        imgs: ["/bej1.jpg", "/bej2.jpg", "/bej3.jpg", "bej4.jpg"],
        title: 'Product 43',
        titleCode: 'product_43',
        color: 'grey',
        category: 'Activewear',
        subcategory: 'Tennis Shorts',
        subcategoryCode: 'tennis_shorts',
        size: 'L',
        quantity: 10,
        bestSellerStatus: 'Best Seller',
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },
    {
        id: 44,
        imgs: ["/purple1.jpg", "/purple2.jpg", "/purple3.jpg", "/purple4.jpg"],
        title: 'Product 44',
        titleCode: 'product_44',
        color: 'mint',
        category: 'Activewear',
        subcategory: 'Tops & Sport Bras',
        subcategoryCode: 'tops_and_sport_bras',
        size: 'S',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },
    {
        id: 45,
        imgs: ["/sb1.jpg", "/sb2.jpg", "/sb3.jpg", "/sb4.jpg"],
        title: 'Product 45',
        titleCode: 'product_45',
        color: 'white',
        category: 'Accessories',
        subcategory: 'Sport Bags',
        subcategoryCode: 'sport_bags',
        size: null,
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },
    {
        id: 46,
        imgs: ["/bej1.jpg", "/bej2.jpg", "/bej3.jpg", "bej4.jpg"],
        title: 'Product 46',
        titleCode: 'product_46',
        color: 'pink',
        category: 'Activewear',
        subcategory: 'Long-sleeve workout tops',
        subcategoryCode: 'long-sleeve_workout_tops',
        size: 'S',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },
    {
        id: 47,
        imgs: ["/corset.jpg"],
        title: 'Product 47',
        titleCode: 'product_47',
        color: 'orange',
        category: 'Accessories',
        subcategory: 'Corsets',
        subcategoryCode: 'corsets',
        size: 'S',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Out of Stock',
    },
    {
        id: 48,
        imgs: ["/purple1.jpg", "/purple2.jpg", "/purple3.jpg", "/purple4.jpg"],
        title: 'Product 48',
        titleCode: 'product_48',
        color: 'cream',
        category: 'Activewear',
        subcategory: 'Tops & Sport Bras',
        subcategoryCode: 'tops_and_sport_bras',
        size: 'S',
        quantity: 10,
        bestSellerStatus: null,
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Out of Stock',
    },
    {
        id: 49,
        imgs: ["/swim1.jpg", "/swim2.jpg", "/swim3.jpg", "/swim4.jpg"],
        title: 'Product 49',
        titleCode: 'product_49',
        color: 'green',
        category: 'Swimwear',
        subcategory: 'Swimwear',
        subcategoryCode: 'swimwear',
        size: 'M',
        quantity: 10,
        bestSellerStatus: 'Best Seller',
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },
    {
        id: 50,
        imgs: ["/sb1.jpg", "/sb2.jpg", "/sb3.jpg", "/sb4.jpg"],
        title: 'Product 50',
        titleCode: 'product_50',
        color: 'grey',
        category: 'Accessories',
        subcategory: 'Sport Bag',
        subcategoryCode: 'sport-bags',
        size: null,
        quantity: 10,
        bestSellerStatus: 'Best Seller',
        newArrival: 'N',
        currency: '$',
        price: 50,
        promo: 'N',
        promoPrice: null,
        availability: 'Available',
    },
];

export const getProducts = () => {
    return products;
}

//cream structura generala pentru a adauga aici produse noi
export const getProductById = (id) => {
    const foundItem = products.find(product => product.id === id);
    const defaultItem = {
        id: null,
        imgs: ["/purple1.jpg", "/purple2.jpg", "/purple3.jpg", "/purple4.jpg"],
        title: '',
        titleCode: '',
        color: '',
        category: '',
        subcategory: '',
        subcategoryCode: '',
        size: '',
        quantity: '', 
        bestSellerStatus: '',
        newArrival: 'N',
        currency: '$',
        price: '',
        promo: 'N',
        promoPrice: null,
        availability: '',
    };
    return foundItem ? foundItem : defaultItem;
};

export const filterProducts = (products, filters) => {
    return products.filter(product => {
      // Check each filter criterion
      const categoryFilter = !filters.category || product.category === filters.category;
      const subcategoryFilter = !filters.subcategory || product.subcategoryCode === filters.subcategory;
      const colorFilter = !filters.color || product.color === filters.color;
      const sizeFilter = !filters.size || product.size === filters.size;
      const availabilityFilter = !filters.availability || product.availability === filters.availability;
  
      // Check price range if provided
      const priceFilter = (!filters.minPrice || product.price >= filters.minPrice) &&
                         (!filters.maxPrice || product.price <= filters.maxPrice);
  
      // Combine all filters with AND logic
      return categoryFilter && subcategoryFilter && colorFilter && sizeFilter &&
             availabilityFilter && priceFilter;
    });
  };

//cream o functie care va adauga produse in lista initiala, dar va si modifica produsul existent daca este cazul. Acum trebuie sa verificam daca produsul are id, atunci trebuie sa il gasim si sa rescriem proprietatile lui cu ceea ce primim aici, ceea ce insemana ca el a fost modificat, iar daca id este null, atunci trebuie sa setam un nou atribut id si sa il adaugam in lista
export const saveProduct = (product) => {
    if (!product.id) {//daca nu avem asa produs
        product.id = products.length + 1;
        products.push(product);
    } else {
        const productIndex = products.findIndex(item => item.id === product.id);

        products[productIndex] = product;
    }
};

//aceatsa functie va gasi indexul produsului si il va sterge prin splice -anume item de pe acel index
export const deleteProduct = (id) => {
    const foundIndex = products.findIndex(product => product.id === id);

    if (foundIndex > -1) {
        products.splice(foundIndex, 1);
    }
};